### ISSUE TITLE
deno 1.5.1 isolatedModules breaking change

### ISSUE THREAD

**Issue by vmasdani** [manyuanrong/dso#36]
Hi, Deno 1.5.1 has a breaking change which outputs error in compilation if `isolatedModules: false` is not provided in `tsconfig.json` while compiling the example in readme

``` 
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Deferred,
  ~~~~~~~~
    at https://deno.land/x/mysql@2.1.0/deps.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Client, ClientConfig } from "./src/client.ts";
                 ~~~~~~~~~~~~
    at https://deno.land/x/mysql@2.1.0/mod.ts:1:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ClientConfig,
  ~~~~~~~~~~~~
    at https://deno.land/x/dso@v1.0.0/deps.ts:8:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ClientConfig,
  ~~~~~~~~~~~~
    at https://deno.land/x/dso@v1.0.0/mod.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { LogLevels, LevelName } from "./levels.ts";
                    ~~~~~~~~~
    at https://deno.land/std@0.61.0/log/mod.ts:13:21

Found 5 errors.
```
I'll send a PR of the new `tsconfig.json` in readme and [in the root dir](https://github.com/manyuanrong/dso/blob/master/tsconfig.json) if needed

**Comment by manyuanrong** [comment]
plz

**Comment by vmasdani** [comment]
done #37
